export { DeploymentPage } from './Deployment'
export { OnBoardingPage } from './Onboarding'
export { WorkloadsPage } from './Workloads'
export { LensesPage } from './Lenses'
export { ChooseWorkloadsRegionPage } from './ChooseWorkloadsRegion'
